### ISSUE TITLE
Error get_election_results() para San Luis

### ISSUE THREAD

**Issue by TuQmano** [PoliticaArgentina/electorAr#2]
Al consultar datos de la provincia de San Luis genera un error

```
> get_election_results(district = "sanluis", category = "presi", round = "gral", year = 1951)
Error: Please select a correct 'district.' Check them with 'show_available_elections()' //
Por favor seleccione un 'district' correcto. Compruebelos con 'show_available_elections(source = 'results')
```

Generado por _naming_ distinto de la categoría. Ver 

https://github.com/PoliticaArgentina/electorAr/blob/main/R/get_election_results.R#L111

**Comment by TuQmano** [comment]
Dos alternativas para arreglar _bug_: 

1. renombrar `.csv`s con misma lógica de los demás  (`sfe`, `sjuan`, etc). 
2.  ajustar nombre de archivos existentes internamente en la función.

**Comment by jpruiznicolini** [comment]
Solución 2: 

Se modifica el valor de la categoría `district` para conservar estilo (`sluis` en vez del `sanluis` que viene de origen, por el nombre de los archivos, similar a otros distritos:`sfe` `sjuan`) 

![imagen](https://github.com/PoliticaArgentina/electorAr/assets/96128473/30d202cb-b607-441b-9dc4-7aebeee0217a)


De ese modo en el "visor" de elecciones disponibles ya figura modificado:  `show_available_elections(source = "results", viewer = T)`

![imagen](https://github.com/PoliticaArgentina/electorAr/assets/96128473/1e8a8514-c02d-4f67-89ca-ec77aed25936)


Luego, se modifica en sentido contrario, el valor  `sluis`  de entrada como parámetro de `district`  en `get_electcion_results()`, el `sanluis` necesario para descargar datos en función del nombre de distrito. 

```
> get_election_results(district = "sluis", category = "presi", round = "gral", year = 1951)
# A tibble: 5 x 8
  category round  year codprov name_prov listas                      votos elect~1
  <chr>    <chr> <dbl> <chr>   <chr>     <chr>                       <dbl>   <dbl>
1 presi    gral   1951 NA      NA        Perón - Quijano (Peronista) 50662   88657
2 presi    gral   1951 NA      NA        Balbín - Frondizi (Unión C~ 11270   88657
3 presi    gral   1951 NA      NA        Pastor - Solano Lima (Demó~  9265   88657
4 presi    gral   1951 NA      NA        Ghioldi - De La Peña (Comu~   241   88657
5 presi    gral   1951 NA      NA        Votos Blancos Y Nulos         764   88657
# ... with abbreviated variable name 1: electores
```
